Shoplister/Models/Store.cs
using System.Collections.Generic;

namespace Shoplister.Models
{
  public class Store
  {
    public Store()
    {
      this.JoinEntities = new HashSet<ItemStore>();
    }

    public int StoreId { get; set; }
    public string StoreName { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<ItemStore> JoinEntities { get; set; }
  }
}

Shoplister/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Shoplister.Models;
using System;

namespace Shoplister.Controllers
{
  [Authorize]
  public class ItemsController : Controller
  {
    private readonly ShoplisterContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ItemsController(UserManager<ApplicationUser> userManager, ShoplisterContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      ViewBag.PageTitle = "View All Items";
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userItems = _db.Items.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userItems.OrderBy(item => item.ItemName).ToList());
    }

    [HttpPost]
    public ActionResult Index (List<Item> myItems)
    {
      foreach(var newItem in myItems)
      {
        var dbItemMatch =_db.Items.FirstOrDefault(dbItem => dbItem.ItemId == newItem.ItemId);
        if(dbItemMatch != null)
        {
          dbItemMatch.Checked = newItem.Checked; 
        }    
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Item item, int StoreId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      item.User = currentUser;

      var dbItemMatch =_db.Items.FirstOrDefault(dbItem => (dbItem.ItemName == item.ItemName) && (dbItem.User == item.User));
      if(dbItemMatch != null)
      {
        dbItemMatch.Checked = false; 
      }
      else
      {
        _db.Items.Add(item);
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Edit(int id)
    {
      var thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    [HttpPost]
    public ActionResult Edit (Item item)
    {
      _db.Entry(item).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Delete(int id)
    {
      var thisItem = _db.Items.FirstOrDefault(dbItem => dbItem.ItemId == id);
      _db.Items.Remove(thisItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult AddStore (int id)
    {
      var thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      ViewBag.StoreId = new SelectList(_db.Stores, "StoreId", "StoreName");
      return View(thisItem);
    }

    [HttpPost]
    public ActionResult AddStore (Item item, int StoreId)
    {
      if (StoreId != 0 && _db.ItemStore
          .Where(dbItemStore => dbItemStore.StoreId == StoreId && dbItemStore.ItemId == item.ItemId)
          .Any() == false)
      {
        _db.ItemStore.Add(new ItemStore() { StoreId = StoreId, ItemId = item.ItemId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }


    [HttpPost]
    public ActionResult DeleteStore(int joinId)
    {
      var joinEntry = _db.ItemStore.FirstOrDefault(entry => entry.ItemStoreId == joinId);
      _db.ItemStore.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Shoplister/Controllers/StoresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Shoplister.Models;
using System;

namespace Shoplister.Controllers
{
  [Authorize]
  public class StoresController : Controller
  {
    private readonly ShoplisterContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public StoresController(UserManager<ApplicationUser> userManager, ShoplisterContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      ViewBag.PageTitle = "View All Stores";
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userStores = _db.Stores.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userStores.OrderBy(store => store.StoreName).ToList());
    }
    
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Store store)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      store.User = currentUser;

      var dbStoreMatch =_db.Stores.FirstOrDefault(dbStore => (dbStore.StoreName == store.StoreName) && (dbStore.User == store.User));
      if(dbStoreMatch == null)
      {
        _db.Stores.Add(store);
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    
    public ActionResult Edit(int id)
    {
      Console.WriteLine(id);
      var thisStore = _db.Stores.FirstOrDefault(store => store.StoreId == id);
      Console.WriteLine(thisStore.StoreName);
      return View(thisStore);
    }

    [HttpPost]
    public ActionResult Edit (Store store)
    {
      _db.Entry(store).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Delete(int id)
    {
      var thisStore = _db.Stores.FirstOrDefault(dbStore => dbStore.StoreId == id);
      _db.Stores.Remove(thisStore);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    public ActionResult Details(int id)
    {
      var thisStore = _db.Stores
        .Include(store => store.JoinEntities)
        .FirstOrDefault(store => store.StoreId == id);
      return View(thisStore.JoinEntities.ToList());
    }

    [HttpPost]
    public ActionResult Details(List<ItemStore> storesItems)
    {
      foreach(var newItem in storesItems)
      {
        var dbItemMatch =_db.Items.FirstOrDefault(dbItem => dbItem.ItemId == newItem.ItemId);
        if(dbItemMatch != null)
        {
          dbItemMatch.Checked = newItem.Item.Checked; 
        }    
      }
      _db.SaveChanges();
      return RedirectToAction("Details");
    }
  }
}

Shoplister/Views/Stores/Create.cshtml
@{
  Layout = "_Layout";
}

@model Shoplister.Models.Store

<h2>Add a New Store</h2>
<hr>
@using (Html.BeginForm())
{
  <div class="container-form">
    @Html.LabelFor(model => model.StoreName):
    @Html.TextBoxFor(model => model.StoreName, new { required = "required"})
  </div>
  <br>
  <input style="color: blue; font-size: 1.2em;" type="submit" value="Add New Store" class="btn btn-success" />
}

Shoplister/Views/Stores/Details.cshtml
@{
  Layout = "_Layout";
}





@model List<Shoplister.Models.ItemStore> 
<div class="store-name">
  <h2>@Html.DisplayName(Model.FirstOrDefault().Store.StoreName)</h2>
</div>
@if (Model.Any())
{
  @using (Html.BeginForm())
  {  
    <div class="container-columns">
      <div class="row">
        <div class="col-sm">
          <h2>Unchecked Items:</h2>
          <hr />
          <ul>
            @for(int i = 0; i < Model.Count; i++)
            {
              @if (Model[i].Item.Checked == false)
              {
                <li>
                  @Html.HiddenFor(x => x[i].ItemId)
                  @Html.CheckBoxFor(x => x[i].Item.Checked, new { @class="checkbox-size" }) &nbsp;
                  @Html.ActionLink(Model[i].Item.ItemName, "Edit", "Items", new { id = Model[i].Item.ItemId }, new { @style="font-size: 1.35em; vertical-align: middle;" })
                  <span style="vertical-align: middle;"> - Notes: @Html.DisplayFor(x => x[i].Item.Notes)</span>
              </li>
            }
          }
        </ul>
        <br>
      </div>
      <div class="col-sm">
        <h2>Checked Items:</h2>
        <hr />
        <ul>
          @for(int i = 0; i < Model.Count; i++)
          {
            @if (Model[i].Item.Checked == true)
            {
              <div class="checked">
                <li>
                  @Html.HiddenFor(x => x[i].ItemId)
                  @Html.HiddenFor(x => x[i].ItemStoreId)
                  @Html.CheckBoxFor(x => x[i].Item.Checked, new { @class="checkbox-size" }) &nbsp;
                  <span style="vertical-align: middle;">@Html.DisplayFor(x => x[i].Item.ItemName, new { @style="font-size: 1.35em;" })</span>
                  @Html.HiddenFor(x => x[i].Item.Notes)
                </li>
              </div>
            }
          }
        </ul>  
      </div>
    </div>
  </div> 
    <input class="btn btn-success" style="color: blue; font-size: 1.2em;" type="submit" value="Check/Uncheck" />
  <br>
  <br>
  }
}
else
{
  <h3>No items have been assigned to this store.</h3>
  <br>
  <br>
}
<button style="font-size: 1.2em;" class="btn btn-success">@Html.ActionLink("Edit Store", "Edit", new { id = Model.FirstOrDefault().Store.StoreId })</button>

Shoplister/Views/Stores/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Shoplister.Models.Store


<h2>Edit This Store</h2>
<hr />
@using (Html.BeginForm())
{
  <div class="container-form">
    @Html.HiddenFor(model => model.StoreId)
    @Html.LabelFor(model => model.StoreName):
    @Html.EditorFor(model => model.StoreName, new {require = "required"})
  </div>
  <br>
  <br>

  <input style="color: blue; font-size: 1.2em;" type="submit" class="btn btn-success" value="Save" />
}

Shoplister/Views/Stores/Index.cshtml
@{
  Layout = "_Layout";
}

@using Shoplister.Models;
@model List<Shoplister.Models.Store>;

<h2>Stores</h2>
<hr>

@if (@Model.Count == 0)
{
  <h3>You haven't added any stores yet!</h3>
}

@foreach (Store store in Model)
{
  <li>@Html.ActionLink($"{store.StoreName}", "Details", new { id = store.StoreId }, new { @style="font-size: 1.35em;" })</li>
}
<br>
<button style="font-size: 1.2em;" class="btn btn-success">@Html.ActionLink("Add New Store", "Create")</button>